"$schema" = "./node_modules/wrangler/config-schema.json"
name = "paperstack"
main = ".open-next/worker.js"
compatibility_date = "2026-03-29"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "paperstack-db"
database_id = "4923e3d6-3fc8-435a-86c7-8551408fa0f4"
remote = true

[[r2_buckets]]
binding = "PAPERSTACK_MEDIA"
bucket_name = "paperstack-media"
remote = true

[ai]
binding = "AI"
remote = true
